# Generated by Django 5.0.4 on 2024-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='comment',
        ),
        migrations.AddField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rating range: 1-5'),
        ),
    ]
