# Generated by Django 5.0.4 on 2024-08-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_image_alter_order_status_and_more'),
        ('accounts', '0011_cart'),
    ]

    operations = [
    ]
