# Generated by Django 5.0.3 on 2024-04-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardlune_app', '0002_account_userprofile_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stardlune_app.account'),
        ),
    ]
